# Exercícios

1. Usando NumPy, importe o [dataset iris](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data) mantendo o seu conteúdo intacto.

In [26]:
import numpy as np

iris_dataset = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris = np.genfromtxt(iris_dataset, delimiter=',', dtype='object', encoding='ascii')

sepallength = iris[:,0].astype(float)
#conferir se estar certo a localizacao da coluna
sepalwidth = iris[:,1].astype(float)

2. Extraia a coluna *species* do dataset importado na questão anterior para um vetor unidimensional.

In [27]:
species = iris[:,4]
species

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicol

3. Calcule a média, mediana e desvio padrão da primeira coluna (sepallength) do dataset Iris.

In [4]:
col0 = iris[:,0].astype(float)
print("A média é:",np.mean(col0))
print("A mediana é:",np.median(col0))
print("Desvio padrao:",np.std(col0))

A média é: 5.843333333333334
A mediana é: 5.8
Desvio padrao: 0.8253012917851409


4. Normalize a coluna (sepallength) do dataset iris de tal forma que o valor mínimo seja zero (0) e o valor máximo seja 1.

In [5]:
sepal_length_max = sepallength.max()
sepal_length_min = sepallength.min()

#Metodo1
sepallength_normalizada = (sepallength - sepal_length_min) / (sepal_length_max - sepal_length_min)

print(sepallength[:2])
print(sepallength_normalizada[:2])

[5.1 4.9]
[0.22222222 0.16666667]


5. Encontre o 5º e o 95º percentil do comprimento das pétalas (sepallength) do dataset Iris.

In [6]:
np.percentile(sepallength, q=[5,95])

array([4.6  , 7.255])

6. Encontre a quantidade de valores ausentes, bem como a posição deles da primeira coluna da coluna comprimento das pétalas (sepallength), dentro do vetor abaixo:

In [7]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("Quantidade de valores ausentes:",np.isnan(iris_2d[:,0]).sum())
print("Posicao deos valores ausentes:", np.where(np.isnan(iris_2d[:,0])))

Quantidade de valores ausentes: 3
Posicao deos valores ausentes: (array([12, 28, 63]),)


7. Filtre o vetor iris_2d do exercício anterior para que ele tenha: (terceira coluna (petallength) > 1.5) && (primeira coluna (sepallength) < 5.0)

In [8]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

condicao = (iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)
iris_2d[condicao]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

8. Selecione as linhas do vetor iris_2d que não contenham valores nan (Not a Number).

In [9]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

any_man_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_man_in_row][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

9. Encontre a correlação entre a primeira coluna (sepallength) e a (terceira coluna (petallength) no vetor iris_2d.

In [10]:
#Correlação entre sepallength e petallength

petallength = iris[:,3].astype(float)

correl = np.corrcoef(sepallength,petallength)
print(correl)

[[1.         0.81795363]
 [0.81795363 1.        ]]


10. Verifique se o vetor iris_2d possui qualquer valor faltante, caso possui deverá retornar True caso contrário False.

In [11]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

quant = np.isnan(iris_2d).sum()

if quant != 0:
    print(True)
else:
    print(False)

False


11. Substitua todas as ocorrências de nan (Not a Number) por zeros em um vetor NumPy.

In [12]:
#importa o arquivo e gera posicoes com nan
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

#imprime na tela os numeros faltantes e suas localizaçoes
print("Quantidade de numeros faltantes:",np.isnan(iris_2d).sum())
print("Localizaçao dos faltantes:", np.where(np.isnan(iris_2d)))
print("\n")

#substitui os nan por 0
iris_2d[np.isnan(iris_2d)] = 0

print("Quantidade de numeros faltantes:",np.isnan(iris_2d).sum())

Quantidade de numeros faltantes: 20
Localizaçao dos faltantes: (array([  7,  10,  17,  20,  21,  27,  29,  49,  63,  66,  73,  77,  83,
        84,  88,  90,  97, 119, 121, 122]), array([2, 1, 0, 3, 0, 3, 3, 2, 0, 3, 2, 2, 2, 3, 1, 1, 1, 2, 2, 3]))


Quantidade de numeros faltantes: 0


12. Encontre e conte os valores únicos da coluna species

In [13]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#captura a quantidade de valores unicos em de cada tipo de especies.
valor = np.array(np.unique(iris[:,4], return_counts=True)).T
for nome, quant in valor:
    print("O tipo",nome,"apareceu",quant, "vezes")

O tipo b'Iris-setosa' apareceu 50 vezes
O tipo b'Iris-versicolor' apareceu 50 vezes
O tipo b'Iris-virginica' apareceu 50 vezes


13. Mapeie terceira coluna (petallength) de tal forma que os valores numéricos sejam substituídos por valores textuais, seguindo de acordo com a tabela abaixo:

| Número               | Classificação                
|:---------------------|:--------------|
| Menor do que 3       | Pequena       |
| entre 3 e 5          | Média         |
| Maior ou Igual a 5   | Grande        |

In [14]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#criando um novo arquivo para manipulação dos dados
iris_3d = iris

#classificação pelo tamanho
peq = iris_3d[:,3].astype(float) < 0.3
media = (iris_3d[:,3].astype(float) >= 0.3) & (iris_3d[:,3].astype(float) < 0.5)
grande = iris_3d[:,3].astype(float) >= 0.5

#mapeando os valores de acordo com o tamanho
iris_3d[peq] = 'Pequena'
iris_3d[media] = 'Media'
iris_3d[grande]= 'Grande'
iris_3d[:,3]

array(['Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Media',
       'Media', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena',
       'Pequena', 'Pequena', 'Pequena', 'Media', 'Media', 'Media',
       'Media', 'Media', 'Pequena', 'Media', 'Pequena', 'Grande',
       'Pequena', 'Pequena', 'Media', 'Pequena', 'Pequena', 'Pequena',
       'Pequena', 'Media', 'Pequena', 'Pequena', 'Pequena', 'Pequena',
       'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Media', 'Media',
       'Pequena', 'Grande', 'Media', 'Media', 'Pequena', 'Pequena',
       'Pequena', 'Pequena', 'Grande', 'Grande', 'Grande', 'Grande',
       'Grande', 'Grande', 'Grande', 'Grande', 'Grande', 'Grande',
       'Grande', 'Grande', 'Grande', 'Grande', 'Grande', 'Grande',
       'Grande', 'Grande', 'Grande', 'Grande', 'Grande', 'Grande',
       'Grande', 'Grande', 'Grande', 'Grande', 'Grande', 'Grande',
       'Grande', 'Grande', 'Grande', 'Grande', 'Grande', 'Grande',
       'Grande', 'Grande', 'Grande', 'Gran

14. Crie uma nova coluna chamada *volume*, preenchida com dados resultantes da seguinte equação:

$$volume=\frac{(~ Pi ~x~ Petallength ~x~ Sepal Length^2 ~)}{3}$$


In [55]:
import math

# Entrada de dados
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

volume = (math.pi * petallength * (sepallength**2))/3

#foi inserido na 5 coluna os valores de volume
iris_4d = np.insert(iris_2d, 5,volume, axis=1)
print(iris_4d)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 5.447521661324701]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 5.028642640846063]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 4.62651878118657]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 4.431740036664]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' 5.235987755982989]
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa' 12.214512237157116]
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa' 6.647610054996001]
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa' 5.235987755982989]
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa' 4.054748918233227]
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa' 2.5143213204230315]
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa' 6.107256118578558]
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa' 4.825486315913922]
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa' 2.412743157956961]
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa' 1.9362682721625089]
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa' 7.045545124450709]
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-seto

15. Usando NumPy e o dataset iris responda: Qual é o segundo maior valor de comprimento de pétala (petallength) da espécie setosa?

In [111]:
#entranda de dados
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


In [ ]:
16. Ordene o dataset iris com base na coluna sepallength de maneira crescente.

```python
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [ ]:
17. Encontre o valor mais frequente da terceira coluna (petallength) do dataset iris.

```python
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [ ]:
18. Encontre a posição da primeira ocorrência de um valor maior do que 1.0 da quarta coluna (petalwidth) do dataset iris.

```python
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [ ]:
19. Obtenha a posição dos top 5 valores maíximos do vetor abaixo:

```python
# Entrada
np.random.seed(100)
vetor = np.random.uniform(1,50, 20)
```

20. Encontre a média de uma coluna numérica agrupada por uma coluna categórica em uma matriz (vetor numpy 2D)

```python
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Saída Esperada
#>  [[b'Iris-setosa', 3.418],
#>  [b'Iris-versicolor', 2.770],
#>  [b'Iris-virginica', 2.974]] 
```